export default class Topics {
  constructor() {
    this.indexes = [];
  }

  loadTopic() {
    return this.topics[this.findIndex()];
  }

  findIndex() {
    let index = Math.floor(Math.random() * this.topics.length);
    if (this.indexes.includes(index)) {
      return this.findIndex();
    } else {
      this.indexes.push(index);
      return index;
    }
  }

  get topics() {
    return [
      ['activities', 'Archery'],
      ['activities', 'Artistry'],
      ['activities', 'Astronomy'],
      ['activities', 'Athletics'],
      ['activities', 'Baseball'],
      ['activities', 'Basketball'],
      ['activities', 'Billiards'],
      ['activities', 'Books'],
      ['activities', 'Boxing'],
      ['activities', 'Boy Scouts'],
      ['activities', 'Buddhism'],
      ['activities', 'Canoes'],
      ['activities', 'Car-race'],
      ['activities', 'Carousel'],
      ['activities', 'Carpentry'],
      ['activities', 'Chess'],
      ['activities', 'Cigarettes'],
      ['activities', 'Cycling'],
      ['activities', 'Dance'],
      ['activities', 'Diving'],
      ['activities', 'Fencing'],
      ['activities', 'Fishing'],
      ['activities', 'Football'],
      ['activities', 'Games'],
      ['activities', 'Golf'],
      ['activities', 'Gymnastics'],
      ['activities', 'Hockey'],
      ['activities', 'Hunting'],
      ['activities', 'Mountaineering'],
      ['activities', 'Painting'],
      ['activities', 'Parachuting'],
      ['activities', 'Playing Cards'],
      ['activities', 'Pottery'],
      ['activities', 'Rugby'],
      ['activities', 'Saddle'],
      ['activities', 'Sailing'],
      ['activities', 'Seesaws'],
      ['activities', 'Skating'],
      ['activities', 'Skiing'],
      ['activities', 'Smoking'],
      ['activities', 'Soccer'],
      ['activities', 'Sports'],
      ['activities', 'Swimming Pool'],
      ['activities', 'Swings'],
      ['activities', 'Tanning'],
      ['activities', 'Tattoos'],
      ['activities', 'Tennis'],
      ['activities', 'Olympic Games'],
      ['activities', 'Tobacco'],
      ['activities', 'Treadmill'],
      ['activities', 'Volleyball'],
      ['activities', 'Water Skiing'],
      ['activities', 'Weaving'],
      ['activities', 'Whistling'],
      ['activities', 'Wrestling'],
      ['animals', 'Aardvark'],
      ['animals', 'Alligators'],
      ['animals', 'Alpacas'],
      ['animals', 'Ants'],
      ['animals', 'Armadillos'],
      ['animals', 'Baboons'],
      ['animals', 'Badger'],
      ['animals', 'Bats'],
      ['animals', 'Bears'],
      ['animals', 'Bees'],
      ['animals', 'Beetles'],
      ['animals', 'Birds'],
      ['animals', 'Buffaloes'],
      ['animals', 'Butterflies'],
      ['animals', 'Camels'],
      ['animals', 'Cats'],
      ['animals', 'Caterpillars'],
      ['animals', 'Cheetahs'],
      ['animals', 'Chipmunk'],
      ['animals', 'Cows'],
      ['animals', 'Coyotes'],
      ['animals', 'Cricket'],
      ['animals', 'Crocodiles'],
      ['animals', 'Deer'],
      ['animals', 'Dinosaurs'],
      ['animals', 'Dogs'],
      ['animals', 'Dolphins'],
      ['animals', 'Donkeys'],
      ['animals', 'Doves'],
      ['animals', 'Ducks'],
      ['animals', 'Eagle'],
      ['animals', 'Eels'],
      ['animals', 'Elephants'],
      ['animals', 'Ferrets'],
      ['animals', 'Fish'],
      ['animals', 'Flamingos'],
      ['animals', 'Foxes'],
      ['animals', 'Frogs'],
      ['animals', 'Geese'],
      ['animals', 'Giraffes'],
      ['animals', 'Goats'],
      ['animals', 'Goldfish'],
      ['animals', 'Gorillas'],
      ['animals', 'Hamsters'],
      ['animals', 'Hippopotamus'],
      ['animals', 'Horses'],
      ['animals', 'Hornets'],
      ['animals', 'Hummingbirds'],
      ['animals', 'Hyenas'],
      ['animals', 'Iguanas'],
      ['animals', 'Insects'],
      ['animals', 'Jaguars'],
      ['animals', 'Jellyfish'],
      ['animals', 'Kangaroos'],
      ['animals', 'Koalas'],
      ['animals', 'Komodo Dragons'],
      ['animals', 'Ladybugs'],
      ['animals', 'Leeches'],
      ['animals', 'Lemurs'],
      ['animals', 'Lions'],
      ['animals', 'Lizards'],
      ['animals', 'Llamas'],
      ['animals', 'Lobsters'],
      ['animals', 'Macaws'],
      ['animals', 'Manta Rays'],
      ['animals', 'Mastadons'],
      ['animals', 'Mice'],
      ['animals', 'Mollusks'],
      ['animals', 'Monkeys'],
      ['animals', 'Mosquitoes'],
      ['animals', 'Moths'],
      ['animals', 'Mules'],
      ['animals', 'Octopuses'],
      ['animals', 'Ostriches'],
      ['animals', 'Otters'],
      ['animals', 'Owls'],
      ['animals', 'Oxen'],
      ['animals', 'Pandas'],
      ['animals', 'Panthers'],
      ['animals', 'Peacocks'],
      ['animals', 'Pelicans'],
      ['animals', 'Penguins'],
      ['animals', 'Pigeons'],
      ['animals', 'Pigs'],
      ['animals', 'Piranhas'],
      ['animals', 'Porcupines'],
      ['animals', 'Possums'],
      ['animals', 'Pythons'],
      ['animals', 'Rabbits'],
      ['animals', 'Raccoons'],
      ['animals', 'Ravens'],
      ['animals', 'Rhinoceroses'],
      ['animals', 'Roosters'],
      ['animals', 'Scorpions'],
      ['animals', 'Sharks'],
      ['animals', 'Sheep'],
      ['animals', 'Shrimp'],
      ['animals', 'Snail'],
      ['animals', 'Snakes'],
      ['animals', 'Sparrows'],
      ['animals', 'Squids'],
      ['animals', 'Swans'],
      ['animals', 'Tarantulas'],
      ['animals', 'Tigers'],
      ['animals', 'Toads'],
      ['animals', 'Turkeys'],
      ['animals', 'Turtles'],
      ['animals', 'Vulture'],
      ['animals', 'Walruses'],
      ['animals', 'Whales'],
      ['animals', 'Wolves'],
      ['animals', 'Worms'],
      ['animals', 'Zebras'],
      ['art', 'Accordions'],
      ['art', 'Albums'],
      ['art', 'Artists'],
      ['art', 'Bass'],
      ['art', 'Bohemians'],
      ['art', 'Cameras'],
      ['art', 'Cellos'],
      ['art', 'Compact Discs'],
      ['art', 'Drawings'],
      ['art', 'Drums'],
      ['art', 'Films'],
      ['art', 'Flutes'],
      ['art', 'Guitars'],
      ['art', 'Harps'],
      ['art', 'Hieroglyphics'],
      ['art', 'Jewelery'],
      ['art', 'Mandolins'],
      ['art', 'Marionettes'],
      ['art', 'Movies'],
      ['art', 'Music'],
      ['art', 'Novels'],
      ['art', 'Pianos'],
      ['art', 'Pipe Organs'],
      ['art', 'Pottery'],
      ['art', 'Puppets'],
      ['art', 'Records'],
      ['art', 'Saxophones'],
      ['art', 'Sculpture'],
      ['art', 'Singing'],
      ['art', 'Sketching'],
      ['art', 'Synthesizers'],
      ['art', 'Trumpets'],
      ['art', 'Typewriters'],
      ['art', 'Ukuleles'],
      ['art', 'Violas'],
      ['art', 'Violins'],
      ['art', 'Writing'],
      ['art', 'Yodeling'],
      ['fiction', 'Aladdin'],
      ['fiction', 'Aliens'],
      ['fiction', 'Alice in Wonderland'],
      ['fiction', 'Bambi'],
      ['fiction', 'Batman'],
      ['fiction', 'Bilbo Baggins'],
      ['fiction', 'Boogeyman'],
      ['fiction', 'Cinderella'],
      ['fiction', 'Donald Duck'],
      ['fiction', 'E.T.'],
      ['fiction', 'Fairies'],
      ['fiction', 'Forrest Gump'],
      ['fiction', 'Freaks'],
      ['fiction', 'Gandalf'],
      ['fiction', 'Giants'],
      ['fiction', 'Harry Potter'],
      ['fiction', 'Hermione Granger'],
      ['fiction', 'Horoscope'],
      ['fiction', 'James Bond'],
      ['fiction', 'Luke Skywalker'],
      ['fiction', 'Mickey Mouse'],
      ['fiction', 'Minnie Mouse'],
      ['fiction', 'Monsters'],
      ['fiction', 'Mother Goose'],
      ['fiction', 'Mummies'],
      ['fiction', 'Muppets'],
      ['fiction', 'Optimus Prime'],
      ['fiction', 'Peter Pan'],
      ['fiction', 'Princess Leia'],
      ['fiction', 'Santa'],
      ['fiction', 'Shrek'],
      ['fiction', 'Snow White'],
      ['fiction', 'Superman'],
      ['fiction', 'The Joker'],
      ['fiction', 'Vampire'],
      ['fiction', 'Werewolves'],
      ['fiction', 'Winnie the Pooh'],
      ['fiction', 'Witch'],
      ['fiction', 'Wolverine'],
      ['fiction', 'Wonder Woman'],
      ['fiction', 'Yoda'],
      ['fiction', 'Zombies'],
      ['food', 'Apples'],
      ['food', 'Bakeries'],
      ['food', 'Bananas'],
      ['food', 'Barbecue'],
      ['food', 'Beef Jerky'],
      ['food', 'Beekeeping'],
      ['food', 'Breads'],
      ['food', 'Breastfeeding'],
      ['food', 'Cappuccino'],
      ['food', 'Carrots'],
      ['food', 'Cheeseburger'],
      ['food', 'Cheeses'],
      ['food', 'Chocolates'],
      ['food', 'Cocoa'],
      ['food', 'Coffee'],
      ['food', 'Cookies'],
      ['food', 'Doughnut'],
      ['food', 'Drink'],
      ['food', 'Eggs'],
      ['food', 'Fortune Cookies'],
      ['food', 'Fried Chicken'],
      ['food', 'Fruit'],
      ['food', 'Garden'],
      ['food', 'Grapes'],
      ['food', 'Grits'],
      ['food', 'Hot Dog'],
      ['food', 'Ice-cream'],
      ['food', 'Jello'],
      ['food', 'Meat'],
      ['food', 'Milkshake'],
      ['food', 'Onion'],
      ['food', 'Pancake'],
      ['food', 'Pepper'],
      ['food', 'Pineapple'],
      ['food', 'Pizza'],
      ['food', 'Pork'],
      ['food', 'Potatoes'],
      ['food', 'Rice'],
      ['food', 'Salt'],
      ['food', 'Sandwich'],
      ['food', 'Sausages'],
      ['food', 'Spice'],
      ['food', 'Sugar'],
      ['food', 'Tomatoes'],
      ['food', 'Vanilla'],
      ['food', 'Vegetables'],
      ['government', 'Agriculture'],
      ['government', 'Aircraft Carrier'],
      ['government', 'Airforce'],
      ['government', 'Army'],
      ['government', 'Budget'],
      ['government', 'CIA'],
      ['government', 'Communism'],
      ['government', 'Congress'],
      ['government', 'Crime'],
      ['government', 'Criminals'],
      ['government', 'Democracy'],
      ['government', 'Execution'],
      ['government', 'Health Insurance'],
      ['government', 'Homeland Security'],
      ['government', 'Judges'],
      ['government', 'Justice'],
      ['government', 'Mayors'],
      ['government', 'Military'],
      ['government', 'Monarchy'],
      ['government', 'Money'],
      ['government', 'Napoleon'],
      ['government', 'Native Americans'],
      ['government', 'Navy'],
      ['government', 'President'],
      ['government', 'Public Education'],
      ['government', 'Racism'],
      ['government', 'Red Cross'],
      ['government', 'Royalty'],
      ['government', 'Senate'],
      ['government', 'Slavery'],
      ['government', 'Socialism'],
      ['government', 'Spies'],
      ['government', 'Taxes'],
      ['government', 'The Economy'],
      ['government', 'Torture'],
      ['government', 'World War II'],
      ['household', 'Backpack'],
      ['household', 'Bathtub'],
      ['household', 'Beds'],
      ['household', 'Bible'],
      ['household', 'Bottle'],
      ['household', 'Bowl'],
      ['household', 'Boxes'],
      ['household', 'Button'],
      ['household', 'Cards'],
      ['household', 'Carpet'],
      ['household', 'Chair'],
      ['household', 'Checkbook'],
      ['household', 'Clock'],
      ['household', 'Coins'],
      ['household', 'Computer'],
      ['household', 'Cups'],
      ['household', 'Desk'],
      ['household', 'Disney Movies'],
      ['household', 'Dress'],
      ['household', 'Drill'],
      ['household', 'Eraser'],
      ['household', 'Fans'],
      ['household', 'Floodlight'],
      ['household', 'Fork'],
      ['household', 'Gate'],
      ['household', 'Gloves'],
      ['household', 'Hammer'],
      ['household', 'Hammocks'],
      ['household', 'Hats'],
      ['household', 'Hose'],
      ['household', 'Junk'],
      ['household', 'Kaleidoscope'],
      ['household', 'Knife'],
      ['household', 'Laundry'],
      ['household', 'Leather jacket'],
      ['household', 'Lighters'],
      ['household', 'Matches'],
      ['household', 'Nail'],
      ['household', 'Necklace'],
      ['household', 'Needle'],
      ['household', 'Newspapers'],
      ['household', 'Pants'],
      ['household', 'Perfume'],
      ['household', 'Pillar'],
      ['household', 'Pillow'],
      ['household', 'Pipes'],
      ['household', 'Postcards'],
      ['household', 'Printer'],
      ['household', 'Radio'],
      ['household', 'Ring'],
      ['household', 'Roof'],
      ['household', 'Rope'],
      ['household', 'Sandpaper'],
      ['household', 'Sewing Machines'],
      ['household', 'Shoes'],
      ['household', 'Shovels'],
      ['household', 'Shower'],
      ['household', 'Spoon'],
      ['household', 'Spotlight'],
      ['household', 'Staircase'],
      ['household', 'Sunglasses'],
      ['household', 'Table'],
      ['household', 'Tapestry'],
      ['household', 'Television'],
      ['household', 'Toilet'],
      ['household', 'Umbrella'],
      ['household', 'Vacuum'],
      ['household', 'Wheelchair'],
      ['household', 'Window'],
      ['nature', 'Adult'],
      ['nature', 'Arms'],
      ['nature', 'Baby'],
      ['nature', 'Boys'],
      ['nature', 'Brain'],
      ['nature', 'Breeze'],
      ['nature', 'Cactus'],
      ['nature', 'Caves'],
      ['nature', 'Child'],
      ['nature', 'Coal'],
      ['nature', 'Comet'],
      ['nature', 'Cotton'],
      ['nature', 'Crystal'],
      ['nature', 'Diamonds'],
      ['nature', 'Disasters'],
      ['nature', 'Dung'],
      ['nature', 'Ears'],
      ['nature', 'Earthquake'],
      ['nature', 'Electricity'],
      ['nature', 'Eyes'],
      ['nature', 'Family'],
      ['nature', 'Feather'],
      ['nature', 'Finger'],
      ['nature', 'Fire'],
      ['nature', 'Flood'],
      ['nature', 'Flower'],
      ['nature', 'Foot'],
      ['nature', 'Fungus'],
      ['nature', 'Gases'],
      ['nature', 'Gemstone'],
      ['nature', 'Girl'],
      ['nature', 'God'],
      ['nature', 'Gold'],
      ['nature', 'Hurricanes'],
      ['nature', 'Icicle'],
      ['nature', 'Jungles'],
      ['nature', 'Leather'],
      ['nature', 'Legs'],
      ['nature', 'Liquid'],
      ['nature', 'Magnet'],
      ['nature', 'Meteor'],
      ['nature', 'Meteorology'],
      ['nature', 'Mist'],
      ['nature', 'Moon'],
      ['nature', 'Motherhood'],
      ['nature', 'Mouth'],
      ['nature', 'Oil'],
      ['nature', 'Outer Space'],
      ['nature', 'Pebble'],
      ['nature', 'Rainbow'],
      ['nature', 'Rock'],
      ['nature', 'Seashells'],
      ['nature', 'Shells'],
      ['nature', 'Skeleton'],
      ['nature', 'Skull'],
      ['nature', 'Snow'],
      ['nature', 'Spirits'],
      ['nature', 'Star'],
      ['nature', 'Stomach'],
      ['nature', 'Sun'],
      ['nature', 'Teeth'],
      ['nature', 'Tongue'],
      ['nature', 'Vaccines'],
      ['nature', 'Volcanoes'],
      ['nature', 'Water'],
      ['nature', 'Winter'],
      ['nature', 'Woman'],
      ['nature', 'Wood'],
      ['occupations', 'Accountant'],
      ['occupations', 'Archaeologist'],
      ['occupations', 'Architect'],
      ['occupations', 'Banker'],
      ['occupations', 'Boss'],
      ['occupations', 'Botanist'],
      ['occupations', 'Butler'],
      ['occupations', 'Chief'],
      ['occupations', 'Clowns'],
      ['occupations', 'Cobblers'],
      ['occupations', 'Electrician'],
      ['occupations', 'Engineering'],
      ['occupations', 'Fireman'],
      ['occupations', 'Fortune Tellers'],
      ['occupations', 'Journalism'],
      ['occupations', 'Librarians'],
      ['occupations', 'Magicians'],
      ['occupations', 'Mailperson'],
      ['occupations', 'Masonry'],
      ['occupations', 'Mechanic'],
      ['occupations', 'Medicine'],
      ['occupations', 'Mining'],
      ['occupations', 'Nurses'],
      ['occupations', 'Paper Delivery'],
      ['occupations', 'Pilot'],
      ['occupations', 'Plumber'],
      ['occupations', 'Police Officer'],
      ['occupations', 'Psychiatrists'],
      ['occupations', 'Shipping'],
      ['occupations', 'Surveyor'],
      ['occupations', 'Tax Collector'],
      ['occupations', 'Teacher'],
      ['occupations', 'Veterinarians'],
      ['occupations', 'Waiters'],
      ['occupations', 'Zookeepers'],
      ['personalities', 'Abraham Lincoln'],
      ['personalities', 'Adolf Hitler'],
      ['personalities', 'Albert Einstein'],
      ['personalities', 'Alfred Hitchcock'],
      ['personalities', 'Angelina Jolie'],
      ['personalities', 'Anne Frank'],
      ['personalities', 'Arnold Schwarzenegger'],
      ['personalities', 'Audrey Hepburn'],
      ['personalities', 'Barack Obama'],
      ['personalities', 'Bill Gates'],
      ['personalities', 'Charles Darwin'],
      ['personalities', 'Dalai Lama'],
      ['personalities', 'Donald Trump'],
      ['personalities', 'Elvis Presley'],
      ['personalities', 'George W Bush'],
      ['personalities', 'Jesse Owens'],
      ['personalities', 'John F Kennedy'],
      ['personalities', 'Lance Armstrong'],
      ['personalities', 'Madonna'],
      ['personalities', 'Marilyn Monroe'],
      ['personalities', 'Martin Luther King Jr'],
      ['personalities', 'Michael Jackson'],
      ['personalities', 'Michael Jordan'],
      ['personalities', 'Muhammad Ali'],
      ['personalities', 'Nelson Mandela'],
      ['personalities', 'Oprah Winfrey'],
      ['personalities', 'Pablo Picasso'],
      ['personalities', 'Paul McCartney'],
      ['personalities', 'Princess Diana'],
      ['personalities', 'Queen Elizabeth II'],
      ['personalities', 'Rosa Parks'],
      ['personalities', 'Steve Jobs'],
      ['personalities', 'Thomas Edison'],
      ['personalities', 'Tom Cruise'],
      ['personalities', 'Vincent Van Gogh'],
      ['personalities', 'Vladimir Putin'],
      ['places', 'Africa'],
      ['places', 'America'],
      ['places', 'Amusement Parks'],
      ['places', 'Asia'],
      ['places', 'Bank'],
      ['places', 'Barber'],
      ['places', 'Bathroom'],
      ['places', 'Blacksmiths'],
      ['places', 'Brewery'],
      ['places', 'Bridge'],
      ['places', 'Cemetery'],
      ['places', 'Central America'],
      ['places', 'Church'],
      ['places', 'Circus'],
      ['places', 'Coffee-shop'],
      ['places', 'Dentist'],
      ['places', 'Drugstores'],
      ['places', 'Earth'],
      ['places', 'Egypt'],
      ['places', 'Europe'],
      ['places', 'Farm'],
      ['places', 'Farmers Markets'],
      ['places', 'Festival'],
      ['places', 'France'],
      ['places', 'Freeway'],
      ['places', 'Funerals'],
      ['places', 'Gas Station'],
      ['places', 'Highway'],
      ['places', 'Hotels'],
      ['places', 'Jamaica'],
      ['places', 'Kitchen'],
      ['places', 'Library'],
      ['places', 'Lighthouses'],
      ['places', 'Mass'],
      ['places', 'Movie Theaters'],
      ['places', 'North Africa'],
      ['places', 'Pharmacy'],
      ['places', 'Planet'],
      ['places', 'Post-office'],
      ['places', 'Prisons'],
      ['places', 'Restaurant'],
      ['places', 'Room'],
      ['places', 'Salvation Army'],
      ['places', 'School'],
      ['places', 'Shop'],
      ['places', 'South America'],
      ['places', 'Spas'],
      ['places', 'Stadiums'],
      ['places', 'The Post Office'],
      ['places', 'Theme Parks'],
      ['places', 'Wedding'],
      ['places', 'Windmills'],
      ['sciences', 'Antennas'],
      ['sciences', 'Cable'],
      ['sciences', 'Cancer'],
      ['sciences', 'Climate Change'],
      ['sciences', 'Code'],
      ['sciences', 'Databases'],
      ['sciences', 'Disease'],
      ['sciences', 'Internet'],
      ['sciences', 'Internet Providers'],
      ['sciences', 'Microscope'],
      ['sciences', 'Microsoft'],
      ['sciences', 'Programming'],
      ['sciences', 'Radar'],
      ['sciences', 'Radiology'],
      ['sciences', 'Robot'],
      ['sciences', 'Satellite'],
      ['sciences', 'Software'],
      ['sciences', 'Telephone'],
      ['sciences', 'Telescope'],
      ['sciences', 'The Cloud'],
      ['sciences', 'Thermometer'],
      ['sciences', 'Videotape'],
      ['sciences', 'X-rays'],
      ['travel', 'Airplane'],
      ['travel', 'Airports'],
      ['travel', 'Boats'],
      ['travel', 'Cars'],
      ['travel', 'Compass'],
      ['travel', 'Ferries'],
      ['travel', 'Flight'],
      ['travel', 'Jet fighter'],
      ['travel', 'Maps'],
      ['travel', 'Motorcycles'],
      ['travel', 'Passport'],
      ['travel', 'Plane'],
      ['travel', 'Railroads'],
      ['travel', 'Rocket'],
      ['travel', 'Ship'],
      ['travel', 'Shipwreck'],
      ['travel', 'Space Shuttle'],
      ['travel', 'Sports-car'],
      ['travel', 'Submarines'],
      ['travel', 'Train'],
      ['travel', 'Tunnel'],
      ['travel', 'Zeppelins'],
      ['violence', 'Atomic Bomb'],
      ['violence', 'Axes'],
      ['violence', 'Coffin'],
      ['violence', 'Death'],
      ['violence', 'Explosive'],
      ['violence', 'Grenade'],
      ['violence', 'Hatchet'],
      ['violence', 'Machine Gun'],
      ['violence', 'Murder'],
      ['violence', 'Ninja Star'],
      ['violence', 'Pistol'],
      ['violence', 'Poison'],
      ['violence', 'Rifle'],
      ['violence', 'Spear'],
      ['violence', 'Sword'],
      ['violence', 'Torch'],
      ['violence', 'Torpedo'],
      ['violence', 'Weapon']
    ];
  }
}
