export default class Topics {
  constructor() {
    this.indexes = [];
  }

  loadTopic() {
    return this.topics[this.findIndex()];
  }

  findIndex() {
    let index = Math.floor(Math.random() * this.topics.length);
    if (this.indexes.includes(index)) {
      return this.findIndex();
    } else {
      this.indexes.push(index);
      return index;
    }
  }

  get topics() {
    return [
      'Accordions',
      'Adult',
      'Aeroplane',
      'Africa',
      'Agriculture',
      'Air',
      'Aircraft Carrier',
      'Airforce',
      'Airplane',
      'Airports',
      'Album',
      'Alligators',
      'Alphabet',
      'America',
      'Amusement Parks',
      'Apes',
      'Apple',
      'Archery',
      'Arm',
      'Army',
      'Art',
      'Artists',
      'Asia',
      'Astronomy',
      'Athletics',
      'Baby',
      'Backpack',
      'Bakeries',
      'Balloons',
      'Bananas',
      'Bank',
      'Barbecue',
      'Barbers',
      'Baseball',
      'Basketball',
      'Bathroom',
      'Bathtub',
      'Bats',
      'Bears',
      'Bed',
      'Bee',
      'Beekeeping',
      'Bible',
      'Billiards',
      'Birds',
      'Blacksmiths',
      'Boats',
      'Bohemians',
      'Bomb',
      'Books',
      'Boss',
      'Bottle',
      'Bowl',
      'Box',
      'Boxing',
      'Boy',
      'Boy Scouts',
      'Brain',
      'Bread',
      'Breastfeeding',
      'Breweries',
      'Bridges',
      'Buddhism',
      'Buffaloes',
      'Butterfly',
      'Button',
      'Cactus',
      'Camels',
      'Canoes',
      'Cappuccino',
      'Car',
      'Car-race',
      'Cards',
      'Carousels',
      'Carpentry',
      'Carpet',
      'Carrot',
      'Cats',
      'Caves',
      'Cemetery',
      'Central America',
      'Chair',
      'Checkbook',
      'Cheese',
      'Chess',
      'Chess Board',
      'Chief',
      'Child',
      'Chisel',
      'Chocolates',
      'Church',
      'Cigarettes',
      'Circle',
      'Circus',
      'Clock',
      'Clowns',
      'Coal',
      'Cobblers',
      'Cocoa',
      'Code',
      'Coffee',
      'Coffee-shop',
      'Coffin',
      'Coins',
      'Comet',
      'Communism',
      'Compact Disc',
      'Compass',
      'Computer',
      'Cotton',
      'Cows',
      'Cricket',
      'Crime',
      'Criminals',
      'Crocodiles',
      'Crystal',
      'Cup',
      'Cycle',
      'Cycling',
      'Dance',
      'Data Base',
      'Death',
      'Dentistry',
      'Desk',
      'Diamonds',
      'Disasters',
      'Disney Movies',
      'Diving',
      'Dogs',
      'Dolphins',
      'Donkeys',
      'Dress',
      'Drill',
      'Drink',
      'Drugstores',
      'Drum',
      'Dung',
      'Ears',
      'Earth',
      'Earthquake',
      'Egg',
      'Electricity',
      'Elephants',
      'Engineering',
      'Eraser',
      'Europe',
      'Execution',
      'Explosive',
      'Eyes',
      'Family',
      'Fan',
      'Farm',
      'Farmers Markets',
      'Feather',
      'Fencing',
      'Ferry Boats',
      'Festival',
      'Film',
      'Finger',
      'Fire',
      'Firemen',
      'Fishing',
      'Flight',
      'Flood',
      'Floodlight',
      'Flower',
      'Foot',
      'Football',
      'Fork',
      'Fortune Tellers',
      'Foxes',
      'France',
      'Freaks',
      'Freeway',
      'Frogs',
      'Fruit',
      'Funerals',
      'Fungus',
      'Games',
      'Garden',
      'Gas',
      'Gas Station',
      'Gate',
      'Geese',
      'Gemstone',
      'Giants',
      'Giraffes',
      'Girl',
      'Gloves',
      'Goats',
      'God',
      'Gold',
      'Golf',
      'Gorillas',
      'Grapes',
      'Guitar',
      'Gymnastics',
      'Gypsies',
      'Hammer',
      'Hammocks',
      'Hat',
      'Hieroglyphics',
      'Highway',
      'Hippopotamus',
      'Hockey',
      'Horoscope',
      'Horses',
      'Hose',
      'Hotels',
      'Hunting',
      'Hurricanes',
      'Ice',
      'Ice-cream',
      'Insects',
      'Jamaica',
      'Jet fighter',
      'Jewelery',
      'Journalism',
      'Jungles',
      'Junk',
      'Justice',
      'Kaleidoscope',
      'Kitchen',
      'Knife',
      'Laundry',
      'Leather',
      'Leather jacket',
      'Leg',
      'Library',
      'Lighters',
      'Lighthouses',
      'Lions',
      'Liquid',
      'Magicians',
      'Magnet',
      'Man',
      'Map',
      'Marionettes',
      'Masonry',
      'Mass',
      'Matches',
      'Maze',
      'Meat',
      'Medicine',
      'Meteor',
      'Meteorology',
      'Microscope',
      'Military',
      'Milkshake',
      'Mining',
      'Mist',
      'Money',
      'Monkeys',
      'Monster',
      'Mosquito',
      'Motherhood',
      'Motorcycles',
      'Mountaineering',
      'Mouth',
      'Movie',
      'Movie Theaters',
      'Mules',
      'Mummies',
      'Muppets',
      'Murderers',
      'Music',
      'Nail',
      'Napoleon',
      'Native Americans',
      'Navy',
      'Necklace',
      'Needle',
      'Newspapers',
      'North Africa',
      'Nurses',
      'Oil',
      'Onion',
      'Ostriches',
      'Outer Space',
      'Paint Brush',
      'Pants',
      'Paper Boys',
      'Parachute',
      'Parachuting',
      'Passport',
      'Pebble',
      'Pendulum',
      'Pepper',
      'Perfume',
      'Pharmacy',
      'Pigeons',
      'Pigs',
      'Pillar',
      'Pillow',
      'Pineapple',
      'Pipe Organs',
      'Pipes',
      'Plane',
      'Planet',
      'Playing Cards',
      'Pocket',
      'Police',
      'Politics',
      'Pork',
      'Post-office',
      'Postcards',
      'Potatoes',
      'Pottery',
      'President',
      'Printer',
      'Printing',
      'Prisons',
      'Programming',
      'Puppets',
      'Pyramid',
      'Rabbits',
      'Radar',
      'Radio',
      'Radiology',
      'Railroads',
      'Rainbow',
      'Record',
      'Red Cross',
      'Restaurant',
      'Rhinoceros',
      'Rice',
      'Rifle',
      'Ring',
      'Robot',
      'Rock',
      'Rocket',
      'Roof',
      'Room',
      'Rope',
      'Royalty',
      'Rugby',
      'Saddle',
      'Sailing',
      'Salt',
      'Salvation Army',
      'Sandpaper',
      'Sandwich',
      'Satellite',
      'School',
      'Seashells',
      'Seesaws',
      'Sewing Machines',
      'Sex',
      'Sharks',
      'Sheep',
      'Shells',
      'Ship',
      'Shipping',
      'Shipwrecks',
      'Shoes',
      'Shop',
      'Shovels',
      'Shower',
      'Signature',
      'Skating',
      'Skeleton',
      'Skiing',
      'Skull',
      'Slave',
      'Slavery',
      'Smoking',
      'Snail',
      'Snakes',
      'Soccer',
      'Socialism',
      'Software',
      'Solid',
      'Sorrow',
      'South America',
      'Space Shuttle',
      'Spas',
      'Spectrum',
      'Sphere',
      'Spice',
      'Spinning',
      'Spiral',
      'Spirits',
      'Spoon',
      'Sports',
      'Sports-car',
      'Spotlight',
      'Square',
      'Stadiums',
      'Staircase',
      'Star',
      'Stomach',
      'Submarines',
      'Sugar',
      'Sun',
      'Sunglasses',
      'Surveyor',
      'Swimming Pool',
      'Swings',
      'Sword',
      'Table',
      'Tanning',
      'Tapestry',
      'Tattoos',
      'Technology',
      'Teeth',
      'Telephone',
      'Telescope',
      'Television',
      'Tennis',
      'The Olympic Games',
      'The Post Office',
      'Thermometer',
      'Tigers',
      'Toads',
      'Tobacco',
      'Toilet',
      'Tongue',
      'Torch',
      'Torpedo',
      'Torture',
      'Train',
      'Treadmill',
      'Triangle',
      'Tunnel',
      'Turtles',
      'Typewriters',
      'Umbrella',
      'Vaccines',
      'Vacuum',
      'Vampire',
      'Vanilla',
      'Vegetables',
      'Veterinarians',
      'Videotape',
      'Volcanoes',
      'Volleyball',
      'Vulture',
      'Water',
      'Water Skiing',
      'Weapon',
      'Weaving',
      'Web',
      'Wedding',
      'Whales',
      'Wheelchair',
      'Whistling',
      'Windmills',
      'Window',
      'Winter',
      'Woman',
      'Women in the Army',
      'Wood',
      'World War 1',
      'Worm',
      'Wrestling',
      'X-rays',
      'Zebras',
      'Zeppelins'
    ];
  }
}
