export default class Topics {
  constructor() {
    this.indexes = [];
  }

  loadTopic() {
    return this.topics[this.findIndex()];
  }

  findIndex() {
    let index = Math.floor(Math.random() * this.topics.length);
    if (this.indexes.includes(index)) {
      return this.findIndex();
    } else {
      this.indexes.push(index);
      return index;
    }
  }

  get topics() {
    return [
      ['activities', 'Archery'],
      ['activities', 'Art'],
      ['activities', 'Astronomy'],
      ['activities', 'Athletics'],
      ['activities', 'Baseball'],
      ['activities', 'Basketball'],
      ['activities', 'Billiards'],
      ['activities', 'Books'],
      ['activities', 'Boxing'],
      ['activities', 'Boy Scouts'],
      ['activities', 'Buddhism'],
      ['activities', 'Canoes'],
      ['activities', 'Car-race'],
      ['activities', 'Carousel'],
      ['activities', 'Carpentry'],
      ['activities', 'Chess'],
      ['activities', 'Cigarettes'],
      ['activities', 'Cycling'],
      ['activities', 'Dance'],
      ['activities', 'Diving'],
      ['activities', 'Fencing'],
      ['activities', 'Fishing'],
      ['activities', 'Football'],
      ['activities', 'Games'],
      ['activities', 'Golf'],
      ['activities', 'Gymnastics'],
      ['activities', 'Hockey'],
      ['activities', 'Hunting'],
      ['activities', 'Mountaineering'],
      ['activities', 'Painting'],
      ['activities', 'Parachuting'],
      ['activities', 'Playing Cards'],
      ['activities', 'Pottery'],
      ['activities', 'Rugby'],
      ['activities', 'Saddle'],
      ['activities', 'Sailing'],
      ['activities', 'Seesaws'],
      ['activities', 'Sex'],
      ['activities', 'Skating'],
      ['activities', 'Skiing'],
      ['activities', 'Smoking'],
      ['activities', 'Soccer'],
      ['activities', 'Sports'],
      ['activities', 'Swimming Pool'],
      ['activities', 'Swings'],
      ['activities', 'Tanning'],
      ['activities', 'Tattoos'],
      ['activities', 'Tennis'],
      ['activities', 'The Olympic Games'],
      ['activities', 'Tobacco'],
      ['activities', 'Treadmill'],
      ['activities', 'Volleyball'],
      ['activities', 'Water Skiing'],
      ['activities', 'Weaving'],
      ['activities', 'Whistling'],
      ['activities', 'Wrestling'],
      ['animals', 'Alligators'],
      ['animals', 'Apes'],
      ['animals', 'Bats'],
      ['animals', 'Bears'],
      ['animals', 'Bee'],
      ['animals', 'Birds'],
      ['animals', 'Buffaloes'],
      ['animals', 'Butterfly'],
      ['animals', 'Camels'],
      ['animals', 'Cats'],
      ['animals', 'Cows'],
      ['animals', 'Cricket'],
      ['animals', 'Crocodiles'],
      ['animals', 'Dogs'],
      ['animals', 'Dolphins'],
      ['animals', 'Donkeys'],
      ['animals', 'Elephants'],
      ['animals', 'Foxes'],
      ['animals', 'Frogs'],
      ['animals', 'Geese'],
      ['animals', 'Giraffes'],
      ['animals', 'Goats'],
      ['animals', 'Gorillas'],
      ['animals', 'Hippopotamus'],
      ['animals', 'Horses'],
      ['animals', 'Insects'],
      ['animals', 'Lions'],
      ['animals', 'Monkeys'],
      ['animals', 'Mosquito'],
      ['animals', 'Mules'],
      ['animals', 'Ostriches'],
      ['animals', 'Pigeons'],
      ['animals', 'Pigs'],
      ['animals', 'Rabbits'],
      ['animals', 'Rhinoceros'],
      ['animals', 'Sharks'],
      ['animals', 'Sheep'],
      ['animals', 'Snail'],
      ['animals', 'Snakes'],
      ['animals', 'Tigers'],
      ['animals', 'Toads'],
      ['animals', 'Turtles'],
      ['animals', 'Vulture'],
      ['animals', 'Whales'],
      ['animals', 'Worm'],
      ['animals', 'Zebras'],
      ['art', 'Accordions'],
      ['art', 'Album'],
      ['art', 'Artists'],
      ['art', 'Balloons'],
      ['art', 'Bass'],
      ['art', 'Bohemians'],
      ['art', 'Cello'],
      ['art', 'Compact Disc'],
      ['art', 'Drawing'],
      ['art', 'Drum'],
      ['art', 'Film'],
      ['art', 'Guitar'],
      ['art', 'Hieroglyphics'],
      ['art', 'Jewelery'],
      ['art', 'Marionettes'],
      ['art', 'Movie'],
      ['art', 'Muppets'],
      ['art', 'Music'],
      ['art', 'Novels'],
      ['art', 'Pipe Organs'],
      ['art', 'Puppets'],
      ['art', 'Record'],
      ['art', 'Sculpture'],
      ['art', 'Singing'],
      ['art', 'Sketching'],
      ['art', 'Typewriters'],
      ['art', 'Viola'],
      ['art', 'Violin'],
      ['art', 'Writing'],
      ['art', 'Yodeling'],
      ['fiction', 'Aladdin'],
      ['fiction', 'Aliens'],
      ['fiction', 'Alive in Wonderland'],
      ['fiction', 'Batman'],
      ['fiction', 'Bilbo Baggins'],
      ['fiction', 'Boogeyman'],
      ['fiction', 'E.T.'],
      ['fiction', 'Forrest Gump'],
      ['fiction', 'Freaks'],
      ['fiction', 'Gandalf'],
      ['fiction', 'Giants'],
      ['fiction', 'Harry Potter'],
      ['fiction', 'Horoscope'],
      ['fiction', 'James Bond'],
      ['fiction', 'Luke Skywalker'],
      ['fiction', 'Monsters'],
      ['fiction', 'Mummies'],
      ['fiction', 'Optimus Prime'],
      ['fiction', 'Princess Leia'],
      ['fiction', 'Santa'],
      ['fiction', 'Superman'],
      ['fiction', 'The Joker'],
      ['fiction', 'Vampire'],
      ['fiction', 'Werewolves'],
      ['fiction', 'Witch'],
      ['fiction', 'Wolverine'],
      ['fiction', 'Wonder Woman'],
      ['fiction', 'Yoda'],
      ['fiction', 'Zombies'],
      ['food', 'Agriculture'],
      ['food', 'Apple'],
      ['food', 'Bakeries'],
      ['food', 'Bananas'],
      ['food', 'Barbecue'],
      ['food', 'Beekeeping'],
      ['food', 'Bread'],
      ['food', 'Breastfeeding'],
      ['food', 'Cappuccino'],
      ['food', 'Carrot'],
      ['food', 'Cheese'],
      ['food', 'Chocolates'],
      ['food', 'Cocoa'],
      ['food', 'Coffee'],
      ['food', 'Drink'],
      ['food', 'Egg'],
      ['food', 'Fruit'],
      ['food', 'Garden'],
      ['food', 'Grapes'],
      ['food', 'Ice-cream'],
      ['food', 'Meat'],
      ['food', 'Milkshake'],
      ['food', 'Onion'],
      ['food', 'Pepper'],
      ['food', 'Pineapple'],
      ['food', 'Pork'],
      ['food', 'Potatoes'],
      ['food', 'Rice'],
      ['food', 'Salt'],
      ['food', 'Sandwich'],
      ['food', 'Spice'],
      ['food', 'Sugar'],
      ['food', 'Vanilla'],
      ['food', 'Vegetables'],
      ['household', 'Backpack'],
      ['household', 'Bathtub'],
      ['household', 'Bed'],
      ['household', 'Bible'],
      ['household', 'Bottle'],
      ['household', 'Bowl'],
      ['household', 'Box'],
      ['household', 'Button'],
      ['household', 'Cards'],
      ['household', 'Carpet'],
      ['household', 'Chair'],
      ['household', 'Checkbook'],
      ['household', 'Clock'],
      ['household', 'Coins'],
      ['household', 'Computer'],
      ['household', 'Cup'],
      ['household', 'Desk'],
      ['household', 'Disney Movies'],
      ['household', 'Dress'],
      ['household', 'Drill'],
      ['household', 'Eraser'],
      ['household', 'Fan'],
      ['household', 'Floodlight'],
      ['household', 'Fork'],
      ['household', 'Gate'],
      ['household', 'Gloves'],
      ['household', 'Hammer'],
      ['household', 'Hammocks'],
      ['household', 'Hat'],
      ['household', 'Hose'],
      ['household', 'Junk'],
      ['household', 'Kaleidoscope'],
      ['household', 'Knife'],
      ['household', 'Laundry'],
      ['household', 'Leather jacket'],
      ['household', 'Lighters'],
      ['household', 'Matches'],
      ['household', 'Nail'],
      ['household', 'Necklace'],
      ['household', 'Needle'],
      ['household', 'Newspapers'],
      ['household', 'Pants'],
      ['household', 'Perfume'],
      ['household', 'Pillar'],
      ['household', 'Pillow'],
      ['household', 'Pipes'],
      ['household', 'Postcards'],
      ['household', 'Printer'],
      ['household', 'Radio'],
      ['household', 'Ring'],
      ['household', 'Roof'],
      ['household', 'Rope'],
      ['household', 'Sandpaper'],
      ['household', 'Sewing Machines'],
      ['household', 'Shoes'],
      ['household', 'Shovels'],
      ['household', 'Shower'],
      ['household', 'Spoon'],
      ['household', 'Spotlight'],
      ['household', 'Staircase'],
      ['household', 'Sunglasses'],
      ['household', 'Table'],
      ['household', 'Tapestry'],
      ['household', 'Television'],
      ['household', 'Toilet'],
      ['household', 'Umbrella'],
      ['household', 'Vacuum'],
      ['household', 'Wheelchair'],
      ['household', 'Window'],
      ['nature', 'Adult'],
      ['nature', 'Air'],
      ['nature', 'Arm'],
      ['nature', 'Baby'],
      ['nature', 'Boy'],
      ['nature', 'Brain'],
      ['nature', 'Cactus'],
      ['nature', 'Caves'],
      ['nature', 'Child'],
      ['nature', 'Coal'],
      ['nature', 'Comet'],
      ['nature', 'Cotton'],
      ['nature', 'Crystal'],
      ['nature', 'Diamonds'],
      ['nature', 'Disasters'],
      ['nature', 'Dung'],
      ['nature', 'Ears'],
      ['nature', 'Earthquake'],
      ['nature', 'Electricity'],
      ['nature', 'Eyes'],
      ['nature', 'Family'],
      ['nature', 'Feather'],
      ['nature', 'Finger'],
      ['nature', 'Fire'],
      ['nature', 'Flood'],
      ['nature', 'Flower'],
      ['nature', 'Foot'],
      ['nature', 'Fungus'],
      ['nature', 'Gas'],
      ['nature', 'Gemstone'],
      ['nature', 'Girl'],
      ['nature', 'God'],
      ['nature', 'Gold'],
      ['nature', 'Hurricanes'],
      ['nature', 'Ice'],
      ['nature', 'Jungles'],
      ['nature', 'Leather'],
      ['nature', 'Leg'],
      ['nature', 'Liquid'],
      ['nature', 'Magnet'],
      ['nature', 'Man'],
      ['nature', 'Meteor'],
      ['nature', 'Meteorology'],
      ['nature', 'Mist'],
      ['nature', 'Motherhood'],
      ['nature', 'Mouth'],
      ['nature', 'Oil'],
      ['nature', 'Outer Space'],
      ['nature', 'Pebble'],
      ['nature', 'Rainbow'],
      ['nature', 'Rock'],
      ['nature', 'Seashells'],
      ['nature', 'Shells'],
      ['nature', 'Skeleton'],
      ['nature', 'Skull'],
      ['nature', 'Spirits'],
      ['nature', 'Star'],
      ['nature', 'Stomach'],
      ['nature', 'Sun'],
      ['nature', 'Teeth'],
      ['nature', 'Tongue'],
      ['nature', 'Vaccines'],
      ['nature', 'Volcanoes'],
      ['nature', 'Water'],
      ['nature', 'Winter'],
      ['nature', 'Woman'],
      ['nature', 'Wood'],
      ['occupations', 'Boss'],
      ['occupations', 'Chief'],
      ['occupations', 'Clowns'],
      ['occupations', 'Cobblers'],
      ['occupations', 'Engineering'],
      ['occupations', 'Firemen'],
      ['occupations', 'Fortune Tellers'],
      ['occupations', 'Journalism'],
      ['occupations', 'Magicians'],
      ['occupations', 'Mailperson'],
      ['occupations', 'Masonry'],
      ['occupations', 'Medicine'],
      ['occupations', 'Mining'],
      ['occupations', 'Nurses'],
      ['occupations', 'Paper Delivery'],
      ['occupations', 'Pilot'],
      ['occupations', 'Plumber'],
      ['occupations', 'Shipping'],
      ['occupations', 'Surveyor'],
      ['occupations', 'Veterinarians'],
      ['places', 'Africa'],
      ['places', 'America'],
      ['places', 'Amusement Parks'],
      ['places', 'Asia'],
      ['places', 'Bank'],
      ['places', 'Barber'],
      ['places', 'Bathroom'],
      ['places', 'Blacksmiths'],
      ['places', 'Brewery'],
      ['places', 'Bridge'],
      ['places', 'Cemetery'],
      ['places', 'Central America'],
      ['places', 'Church'],
      ['places', 'Circus'],
      ['places', 'Coffee-shop'],
      ['places', 'Dentist'],
      ['places', 'Drugstores'],
      ['places', 'Earth'],
      ['places', 'Egypt'],
      ['places', 'Europe'],
      ['places', 'Farm'],
      ['places', 'Farmers Markets'],
      ['places', 'Festival'],
      ['places', 'France'],
      ['places', 'Freeway'],
      ['places', 'Funerals'],
      ['places', 'Gas Station'],
      ['places', 'Highway'],
      ['places', 'Hotels'],
      ['places', 'Jamaica'],
      ['places', 'Kitchen'],
      ['places', 'Library'],
      ['places', 'Lighthouses'],
      ['places', 'Mass'],
      ['places', 'Movie Theaters'],
      ['places', 'North Africa'],
      ['places', 'Pharmacy'],
      ['places', 'Planet'],
      ['places', 'Post-office'],
      ['places', 'Prisons'],
      ['places', 'Restaurant'],
      ['places', 'Room'],
      ['places', 'Salvation Army'],
      ['places', 'School'],
      ['places', 'Shop'],
      ['places', 'South America'],
      ['places', 'Spas'],
      ['places', 'Stadiums'],
      ['places', 'The Post Office'],
      ['places', 'Wedding'],
      ['places', 'Windmills'],
      ['politics', 'Airforce'],
      ['politics', 'Army'],
      ['politics', 'Budget'],
      ['politics', 'Communism'],
      ['politics', 'Crime'],
      ['politics', 'Criminals'],
      ['politics', 'Execution'],
      ['politics', 'Justice'],
      ['politics', 'Military'],
      ['politics', 'Money'],
      ['politics', 'Napoleon'],
      ['politics', 'Native Americans'],
      ['politics', 'Navy'],
      ['politics', 'Police'],
      ['politics', 'Politics'],
      ['politics', 'President'],
      ['politics', 'Red Cross'],
      ['politics', 'Royalty'],
      ['politics', 'Slavery'],
      ['politics', 'Socialism'],
      ['politics', 'Taxes'],
      ['politics', 'Torture'],
      ['politics', 'Women in the Army'],
      ['politics', 'World War I'],
      ['politics', 'World War II'],
      ['technology', 'Code'],
      ['technology', 'Database'],
      ['technology', 'Internet'],
      ['technology', 'Microscope'],
      ['technology', 'Microsoft'],
      ['technology', 'Programming'],
      ['technology', 'Radar'],
      ['technology', 'Radiology'],
      ['technology', 'Robot'],
      ['technology', 'Satellite'],
      ['technology', 'Software'],
      ['technology', 'Telephone'],
      ['technology', 'Telescope'],
      ['technology', 'The Cloud'],
      ['technology', 'Thermometer'],
      ['technology', 'Videotape'],
      ['technology', 'Web'],
      ['technology', 'X-rays'],
      ['travel', 'Aircraft Carrier'],
      ['travel', 'Airplane'],
      ['travel', 'Airports'],
      ['travel', 'Boats'],
      ['travel', 'Car'],
      ['travel', 'Compass'],
      ['travel', 'Ferry Boats'],
      ['travel', 'Flight'],
      ['travel', 'Jet fighter'],
      ['travel', 'Map'],
      ['travel', 'Motorcycles'],
      ['travel', 'Passport'],
      ['travel', 'Plane'],
      ['travel', 'Railroads'],
      ['travel', 'Rocket'],
      ['travel', 'Ship'],
      ['travel', 'Shipwreck'],
      ['travel', 'Space Shuttle'],
      ['travel', 'Sports-car'],
      ['travel', 'Submarines'],
      ['travel', 'Train'],
      ['travel', 'Tunnel'],
      ['travel', 'Zeppelins'],
      ['violence', 'Atomic Bomb'],
      ['violence', 'Axe'],
      ['violence', 'Coffin'],
      ['violence', 'Death'],
      ['violence', 'Explosive'],
      ['violence', 'Grenade'],
      ['violence', 'Hatchet'],
      ['violence', 'Machine Gun'],
      ['violence', 'Murderers'],
      ['violence', 'Ninja Star'],
      ['violence', 'Pistol'],
      ['violence', 'Poison'],
      ['violence', 'Rifle'],
      ['violence', 'Spear'],
      ['violence', 'Sword'],
      ['violence', 'Torch'],
      ['violence', 'Torpedo'],
      ['violence', 'Weapon']
    ];
  }
}
